### ISSUE TITLE
NullReferenceException in SetSubscription

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [microsoftgraph/msgraph-training-azurefunction-csharp#6]
**Where did you get the code?**

- [X] Downloaded from GitHub
- [ ] Downloaded from the [Microsoft Graph quick start tool](https://developer.microsoft.com/graph/quick-start)
- [ ] Followed the tutorial from [Microsoft Graph tutorials](https://docs.microsoft.com/graph/tutorials)

**Describe the bug**
I followed steps described in tutorial https://docs.microsoft.com/en-us/graph/tutorials/azure-functions.
When I use frontend app and try to subscribe I receive NullReferenceException
   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GraphTutorial.SetSubscription.<Run>d__3.MoveNext() in C:\Work\msgraph-training-azurefunction-csharp\demo\GraphTutorial\SetSubscription.cs:line 101

**To Reproduce**

1. As in tutorial launch ngrok set secretes
2. Launch azure functions in visual studio
3. launch test app from command line as described in tutorial
4. Open frontend app in browser
5. go to subscribtions tab and try to subscribe user

**Expected behavior**
App should allow to subscribe used

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: chrome
- Version: 89

**Dependency versions**

- Authentication library (MSAL, etc.) version: as in repository
- Graph library (Graph SDK, REST library, etc.) version: as in repository

**Additional context**

**Comment by jasonjoh** [comment]
Sorry you're having trouble @AdaskoTheBeAsT. I can't reproduce the error you're describing with the code in this repository. Do you have your code somewhere I could take a look?
